name: icharts
version: 0.13.5
description: Material Design charting library for flutter.
  Forked from google/charts and updated to the latest SDK and packages.
  Some charts have been modified for large-screen display.
homepage: https://github.com/inoerp/icharts
publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  collection: ^1.14.5
  intl: ^0.19.0
  logging: ^1.0.2
  meta: ^1.1.1
  icharts_common:
    path: '../icharts_common'



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.0.0
  build_runner: 2.4.9
  lints: ^2.0.1


