name: example
description: Charts-Flutter Demo

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  icharts:
    path: ../
  cupertino_icons: ^0.1.0
  intl: ^0.18.0
  logging: ^1.0.2
  meta: ^1.1.1

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
